trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'NomDeConnexionACR'
  imageRepository: 'scraper-app'
  containerRegistry: 'ton-registre.azurecr.io'
  dockerfilePath: 'Dockerfile'
  tag: 'latest'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.10'
  displayName: 'Use Python 3.10'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: Docker@2
  inputs:
    containerRegistry: $(dockerRegistryServiceConnection)
    repository: $(imageRepository)
    command: buildAndPush
    Dockerfile: $(dockerfilePath)
    tags: |
      $(tag)
  displayName: 'Build and Push Docker image'
